### ISSUE TITLE
Excellent article

### ISSUE THREAD

**Issue by wineds** [arnarg/tx3-mini-arch-linux-build#1]
Just watched to thank you for the most excellent, well written, entertaining and technically brilliant article on the tx3 and mainline Linux.  A thoroughly enjoyable and educational read.  Thanks to you I am now using that old tx3 to do audio DSP using camilladsp on archlinux.

**Comment by arnarg** [comment]
Thank you! It's been quite a while!

Is everything in the blog post still working to produce an up to date arch Linux image?

**Comment by wineds** [comment]
Yes still using it and updating to current arch Linux arm release now.
